# Sample Reusable Workflow for building a React app
on:
  workflow_call:
  
    inputs:

      artifact:
        required: true
        type: string

      path:
        default: .
        type: string

jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
      # Checks out the code from the repository of the calling workflow
      - uses: actions/checkout@v3

      # Install the Node.js dependencies, uses caching to save time
      #- name: Use Node.js ${{ matrix.node-version }}
      #  uses: actions/setup-node@v3
      #  with:
      #    node-version: 16.x
      #    cache: npm

      # Install dependencies, build, run unit tests
      - run: |
          pwd
          dir
          cd ${{ inputs.path }}
          pwd
          dir
          npm ci
          npm run build --if-present
          npm test
          dir

      # Publish the build artifact
      - name: Public build artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: ${{ inputs.artifact }}
          path: .
