# Sample Reusable Workflow for building a React app
on:
  workflow_call:
  
    inputs:

      artifact:
        required: true
        type: string

      path:
        default: .
        type: string

jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
      # Checks out the code from the repository of the calling workflow
      - uses: actions/checkout@v3

      # Install dependencies
      - name: Install Dependencies
        run: |
          cd ${{ inputs.path }}
          npm ci

      # Build
      - name: Build Project
        run: |
          cd ${{ inputs.path }}
          npm run build --if-present
          dir
          dir build

      # Run unit tests
      - name: Run Tests
        run: |
          cd ${{ inputs.path }}
          npm test

      # Publish build artifact
      - name: Publish Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: ${{ inputs.artifact }}
          path: ${{ inputs.path }}/build
