# Sample Reusable Workflow for building a React app
on:
  workflow_call:
    # Accepts an input named 'project'
    inputs:
      project:
        required: true
        type: string
    # Accepts a secret input named 'token'
    secrets:
      token:
        required: true

jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
      # Checks out the code from the repository of the calling workflow
      - uses: actions/checkout@v3

      # Install the Node.js dependencies, uses caching to save time
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm

      # Install dependencies, build, run unit tests
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

      # Publish the build artifact
      - name: Public build artifact
        uses: actions/upload-artifact@3.1.0
        with:
          name: build
          path: .
