# Sample Reusable Workflow for building a React app
on:
  workflow_call:
    # Accepts an input named 'project'
    inputs:
      project:
        required: true
        type: string
    # Accepts a secret input named 'token'
    secrets:
      token:
        required: true

jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
      # Checks out the code from the repository of the calling workflow
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo "Hello this is a workflow to build and deploy the ${{ inputs.project }} React application"
